
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: scratch_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./groupproject/backend:/var/www/html  #path to php files
      - ./groupproject/frontend:/var/www/html/frontend  #path to frontend files
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
